name: Site Edit Request
description: Request a change to the Upfront website
title: "[Site Edit] "
labels: ["site-edit"]
body:
  - type: dropdown
    id: page
    attributes:
      label: What page needs to be changed?
      description: Select the page you want to edit, or choose "Other" if it's not listed.
      options:
        - Homepage
        - About page
        - Contact page
        - Case Studies (listing page)
        - Case Study - Maryland Family Network
        - Case Study - North Carolina
        - Case Study - Denver Preschool Program
        - Case Study - Military
        - Resources (listing page)
        - Who We Serve - Government Organizations
        - Who We Serve - CCR&Rs
        - Header/Navigation
        - Footer
        - Other (describe below)
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: What should change?
      description: Describe what you want to add, remove, or modify. Be as specific as you can.
      placeholder: |
        Examples:
        - "Change the headline to say 'New Headline Here'"
        - "Add a new testimonial from John Smith, CEO of Example Org"
        - "Update the phone number in the footer to 555-123-4567"
        - "Add a new case study about our work with XYZ Organization"
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: Reference links or images (optional)
      description: Add any links, screenshots, or images that might help explain what you want.
      placeholder: Paste links or drag images here
    validations:
      required: false
